name: telegram
version: 1.0.0
description: "A library for telegram mtproto api "
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  convert: ^3.0.0
  crclib: ^3.0.0
  crypto: ^3.0.0

  pointycastle:
    git: https://github.com/bcgit/pc-dart.git



